### ISSUE TITLE
COPR package

### ISSUE THREAD

**Issue by RadioAndrea** [savedra1/clipse#116]
I have never packaged a package before, but I packaged this package.

https://copr.fedorainfracloud.org/coprs/azandure/clipse/

Please provide feedback/feel free to offer this as an install option for fedora/RHEL/centos.

**Comment by savedra1** [comment]
Wow thank you for packaging this package! All looks good to me :blue_heart: Would you like to add the instructions to the README yourself? If so feel free to raise a PR and I'll merge, otherwise LMK and I'll get this added :smile:

**Comment by savedra1** [comment]
I've added this to the Readme! feel free to suggest changes and thank you again :blue_heart:
