### ISSUE TITLE
[Feature request] display images using kitty kitten icat

### ISSUE THREAD

**Issue by ser** [savedra1/clipse#117]
`Kitty` terminal has built-in image previews:
 
https://sw.kovidgoyal.net/kitty/kittens/icat/

I think it would be cool to utilise it in `clipse` and probably super easy to deploy.

**Comment by savedra1** [comment]
Hi @ser :wave: 

Thank you for raising this!

Are you suggesting that `icat` could be used as an alternative method for rendering the image previews? I assume this would only be possible for users of `kitty`? I'll investigate the benefits to doing this (better image quality for example) and see if it would be worth implementing :smile:

**Comment by ser** [comment]
Yes, we are limited to kitty users only, but it's a really fast and simple to use image rendering.

**Comment by howyay** [comment]
> Are you suggesting that `icat` could be used as an alternative method for rendering the image previews? I assume this would only be possible for users of `kitty`? I'll investigate the benefits to doing this (better image quality for example) and see if it would be worth implementing 😄

I believe that it won't be worth implementing this feature specifically for kitty's protocol. It's likely more preferable to make the rendering pipeline entirely customizable - this way, users of terminals that support sixel can use sixel.

**Comment by ztmzzz** [comment]
I have successfully displayed images in terminals (foot) that support Sixel. Are there any plans to add this feature? There is still some work to be done, such as adjusting the display position and attempting to fallback to the original method, etc.
![image](https://github.com/user-attachments/assets/d960dab2-e46f-4989-9e43-99fb7fda0e3a)

**Comment by savedra1** [comment]
> I have successfully displayed images in terminals (foot) that support Sixel. Are there any plans to add this feature? There is still some work to be done, such as adjusting the display position and attempting to fallback to the original method, etc. ![image](https://private-user-images.githubusercontent.com/41851415/367532736-d960dab2-e46f-4989-9e43-99fb7fda0e3a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY0MDc0NTYsIm5iZiI6MTcyNjQwNzE1NiwicGF0aCI6Ii80MTg1MTQxNS8zNjc1MzI3MzYtZDk2MGRhYjItZTQ2Zi00OTg5LTllNDMtOTlmYjdmZGEwZTNhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE1VDEzMzIzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNmMWJjMTM1MWRiYWE4MDE4MzM0OGQ1MzJhZmQ2NmM2NWY2NjAxNTJiNDRiMjQ3NjBhMjBlYmNhYjI3ZWJiNjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.psm1isJ-u41qP9r3sQmk-Na8E3yIQUTjhrk1P4NCcsE)

Wow @ztmzzz that looks great!

I'm low on free time at the moment but if you raise this as a PR I can certainly look into getting that implemented into the core project. The only thing to be aware of for something like this is to add a check for the terminal environment at the start of the program, so `clipse` knows which protocol to use for displaying images (Sixel/iCat etc) as each environment will have its own supported methods. In most cases this can be retrieved with `os.Getenv("TERM")` but some environments may differ in how that value is ascertained. 

Also if Sixel requires being installed as a separate dependency, that's something else the program would need to check/handle. 

I appreciate you looking into this, thanks :smile:

**Comment by ztmzzz** [comment]
I use [go-sixel](https://github.com/mattn/go-sixel) to encode images. It might be need to maintain a list to check terminal support or let users enable this feature in configuration file (I prefer this approach).
Sixel support is determined by the user's terminal and doesn't require installing extra packages. One advantage is that if the terminal doesn't support Sixel, it will simply display the Sixel image as blank.
