### ISSUE TITLE
Feature Request: Customizable Keybindings

### ISSUE THREAD

**Issue by TiagoRibeiro25** [savedra1/clipse#135]
### Description
Currently, clipse provides Vim-like keybindings for navigation in the TUI, but there is no way to customize or reassign these keybindings to match user preferences or workflows. I would like to request the addition of a feature that allows users to customize keybindings within the TUI.

### Proposed Solution
**Configuration file:** Add a section in the existing config.json file (or a separate file) for customizable keybindings, where users can define their own mappings for the TUI commands.

**Comment by savedra1** [comment]
Hi @TiagoRibeiro25 :wave: 

Thanks for getting in touch. This has been on the list for a while now, I'm definitely in favour of implementing this in the way you have suggested. 

I do not currently have much free time to work on this myself but will get around to when when I can. In the meantime I am welcoming PRs!

**Comment by savedra1** [comment]
@TiagoRibeiro25 That's merged. Thanks again! 

I think some other features are being worked on so I will give that some time before publishing the next release. 

Great work 👍
