### ISSUE TITLE
[BUG] Unable to start search with 'a', 'f', 'g', 'i' in Linux (Hyprland)

### ISSUE THREAD

**Issue by aayushrathor** [savedra1/clipse#148]
In Hyprland, searching with '/' is broken when the filter string starts with the letters 'a', 'f', 'g', or 'i'. This issue is reproducible in terminal kitty and alacritty.

Error Log:

$ clipse
`Caught panic:

runtime error: index out of range [1] with length 1

Restoring terminal...

goroutine 39 [running]:
runtime/debug.Stack()
	runtime/debug/stack.go:26 +0x5e
runtime/debug.PrintStack()
	runtime/debug/stack.go:18 +0x13
github.com/charmbracelet/bubbletea.(*Program).recoverFromPanic(0xc00009e000)
	github.com/charmbracelet/bubbletea@v1.1.1/tea.go:705 +0x8b
panic({0x5818f9f2e220?, 0xc000e26558?})
	runtime/panic.go:785 +0x132
github.com/sahilm/fuzzy.FindFromNoSort({0xc000e28bcc?, 0xc0000122a0?}, {0x5818f9f488d0, 0xc0000122a0})
	github.com/sahilm/fuzzy@v0.1.1/fuzzy.go:136 +0x945
github.com/sahilm/fuzzy.FindFrom({0xc000e28bcc?, 0x8b1?}, {0x5818f9f488d0?, 0xc0000122a0?})
	github.com/sahilm/fuzzy@v0.1.1/fuzzy.go:99 +0x25
github.com/sahilm/fuzzy.Find(...)
	github.com/sahilm/fuzzy@v0.1.1/fuzzy.go:83
github.com/charmbracelet/bubbles/list.DefaultFilter({0xc000e28bcc, 0x1}, {0xc0003be000?, 0x8?, 0x0?})
	github.com/charmbracelet/bubbles@v0.20.0/list/list.go:89 +0x52
github.com/charmbracelet/bubbles/list.(*Model).handleFiltering.filterItems.func1()
	github.com/charmbracelet/bubbles@v0.20.0/list/list.go:1228 +0x1b5
github.com/charmbracelet/bubbletea.(*Program).handleCommands.func1.1()
	github.com/charmbracelet/bubbletea@v1.1.1/tea.go:324 +0x7d
created by github.com/charmbracelet/bubbletea.(*Program).handleCommands.func1 in goroutine 69
	github.com/charmbracelet/bubbletea@v1.1.1/tea.go:318 +0x131
goroutine 1 [running]:
runtime/debug.Stack()
	runtime/debug/stack.go:26 +0x5e
runtime/debug.PrintStack()
	runtime/debug/stack.go:18 +0x13
github.com/savedra1/clipse/utils.HandleError({0x5818f9f47c20, 0xc000648180})
	github.com/savedra1/clipse/utils/err.go:11 +0x2c
main.launchTUI()
	github.com/savedra1/clipse/main.go:96 +0x77
main.main()
	github.com/savedra1/clipse/main.go:50 +0xc5`

$ clipse
goroutine 1 [running]:
runtime/debug.Stack()
	runtime/debug/stack.go:26 +0x5e
runtime/debug.PrintStack()
	runtime/debug/stack.go:18 +0x13
github.com/savedra1/clipse/utils.HandleError({0x5b4f2d40cc20, 0xc00071c160})
	github.com/savedra1/clipse/utils/err.go:11 +0x2c
main.launchTUI()
	github.com/savedra1/clipse/main.go:96 +0x77
main.main()
	github.com/savedra1/clipse/main.go:50 +0xc5

![image](https://github.com/user-attachments/assets/7aa947bb-7ac7-4252-a828-3365ec12bd01)

**Comment by savedra1** [comment]
This is caused by some image binary data not being compatible with the fuzzy find algo.

Basically, there will be an image with an irregular binary pattern (or potentially a string value for a non ascii compatible character) in your history. 

Running `clipse -clear-images` should resolve, but let me know if that doesn't help. 

Thanks for raising this

**Comment by aayushrathor** [comment]
Thanks for replying.

clearing image data did not work however resetting config and clearing text history worked.

**Comment by beyertom** [comment]
I've experienced the same issues multiple times. Clearing the images doesn't resolve the problem; however, it starts working again as soon as I clear the history or when a seemingly defective entry is automatically forgotten.

This is quite frustrating, as I have a long history I'd like to keep. Is there anything I can do to debug the issue?

Thanks a alot!

**Comment by savedra1** [comment]
Hi @beyertom, 

The fuzzy find algo that's used is baked into the BubbleTea library, so it's difficult to implement a reliable fix without contributing the change to the BubbleTea source code. 

There is a potential workaround I can think of... If the problematic characters can be identified, logic can be added to the clipse program that removes these characters from the display value in the TUI, while keeping the original values when an item is copied. This should be enough to stop the program crashing, but requires knowing what types of chars will cause a panic, and this may even vary across different terminal environments. 

Currently I'm lacking free time to be able to test this but if you can identify the specific types of characters causing the issue I can get it coded in when possible. Also feel free to raise a PR for the above. 

Thanks

**Comment by beyertom** [comment]
Thank you for your reply. I'll investigate further when the issue occurs again. If I identify the problematic characters, I'll post them here. Cheers.
