### ISSUE TITLE
[Feature] Donation Page

### ISSUE THREAD

**Issue by catdotjs** [savedra1/clipse#161]
I really love this software! It's one of the rare clipboards that actually works across xwayland, wayland and really anything else. If you are up for it, you should really set up a donation page.

**Comment by savedra1** [comment]
@catdotjs Thank you so much for the kind words and the support for the project, I'm happy to hear you're finding it useful. 

It was never my intention to monetize clipse and lately I'm not able to dedicate much time to it, so for now I won't be setting up donations. 

Your feedback is more than enough!

If you'd like to support the project further, sharing it with others or contributing bug reports/ideas would also go a long way. 

Thanks again for reaching out, it's much appreciated. 

🚀

**Comment by catdotjs** [comment]
Thanks for the answer. While I am not too experienced with Go I'll see if I can help with some bug fixing. I'll be closing this issue.

**Comment by chris-wood20** [comment]
Hi @savedra1 

I completely understand and appreciate your earlier response about not wanting to monetise clipse it’s already such a great tool, and the fact that it just works across xwayland, wayland, and everything else is amazing.

That said, I really think this project deserves a simple “Buy Me a Coffee” or donation link not necessarily to monetise it, but as an easy way for users who genuinely appreciate your work to show support. It doesn’t have to be about income, just an optional gesture of thanks for the effort and polish you’ve already put into clipse.

Even if development slows down, lots of us would love a way to give back a little bit for such a high-quality, reliable project.

Would you consider reopening this issue?

**Comment by savedra1** [comment]
@chris-wood20 Thank you for your kind words ❤️ 

I have now added a ko-fi link for donations 😄
