### ISSUE TITLE
Improvement: Hitting Enter should copy what u selected then close the window

### ISSUE THREAD

**Issue by skela** [savedra1/clipse#17]
I think its a sensible and expected user experience, but if not, could we have a setting or config for it to make it so?

Love this program, already started using it in Hyprland. So happy to not do this via rofi anymore.

**Comment by savedra1** [comment]
Thanks for raising this @skela 

You'll be pleased to know that this functionality already exists for all Linux builds. What command did you bind for opening the TUI? If you bind 'clipse $PPID' that should achieve the 'close on selection' effect you're looking for. 

If using MacOs, sadly this does not kill the terminal window. Have been looking into a fix but AFAIK it requires a lot of complex system adjustments by the user. 

Let me know if this helps!

Cheers

**Comment by skela** [comment]
I'm using linux, endevour OS to be specific (not that that should matter here).
I've got this in my hyprland config:
`bind = CONTROL ALT, C, exec, kitty --class floating -e fish  -c 'clipse $PPID' `

And this in my waybar config:


```
"custom/clipboard": {
		"format": "",
		"interval": "once",
		"return-type": "json",
		"on-click": "kitty --class floating -e fish  -c 'clipse $PPID'",
		"on-click-right": "kitty --class floating -e fish  -c 'clipse $PPID'",
		"on-click-middle": "clipse -clear",
		// "on-click": "/home/skela/.dotfiles/scripts/launcher-clipboard.sh left",
		// "on-click-right": "/home/skela/.dotfiles/scripts/launcher-clipboard.sh right",
		// "on-click-middle": "cliphist wipe",
		"exec": "printf '{\"tooltip\":\"%s\"}' $(cliphist list | wc -l)",
		// "exec-if": "[ -x \"$(command -v cliphist)\" ] && [ $(cliphist list | wc -l) -gt 0 ]",
		"signal": 9
	}


```

**Comment by skela** [comment]
Ok, i might have figured out why it wasnt working.

I was passing in fish as my environment, having also tried /usr/bin/fish, with it seemingly working, so thought that was all good.

But after replacing fish with bash, it closes the window when I hit enter.

So might be an issue specific to the fish shell iand clipse.

**Comment by savedra1** [comment]
Love the idea of adding this to the waybar! Might copy you there. 

As for the not closing.. you're bind seems perfect already so must be something else going wrong. Do you get a status message in the TUI after selection? I'd recommend checking the following:

- In a standard terminal session, run `echo $PPID` then run run `kill <the ppid returned>` to see if that closes the terminal window. If not, the issue lies with your terminal environment, similar to MacOs. If it does, try hardcoding a returned PPID from a new echo command into a direct session, eg. `clipse 17223`. If this works, the error lies with how the `$PPID` var is being parsed in the binding
- Any system errors/panics should create a `.config/clipse/err_log.txt` file, maybe better debugging info in there. 
- It's possible that different terminal environments use `$PPID` & `$PID` interchangeably so could be worth trying `clipse $PID`  

hopefully this gets you somewhere

**Comment by skela** [comment]
both echo $PPID and echo $PID return nothing.
![image](https://github.com/savedra1/clipse/assets/58268/9f854cd8-4457-4cba-a3c7-95b9b3b76328)

**Comment by savedra1** [comment]
> Ok, i might have figured out why it wasn't working.
> 
> I was passing in fish as my environment, having also tried /usr/bin/fish, with it seemingly working, so thought that was all good.
> 
> But after replacing fish with bash, it closes the window when I hit enter.
> 
> So might be an issue specific to the fish shell and clipse.


Ah! that's super good to know, thank you for letting me know. Will keep an eye out for that in the future.

**Comment by skela** [comment]
Found this variable in fish that lets me kill it:

![image](https://github.com/savedra1/clipse/assets/58268/33afd360-72a7-4fe7-9445-44440a825e9b)

**Comment by skela** [comment]
So yeah, this bind works for me in fish:
`bind = CONTROL ALT, C, exec, kitty --class floating -e fish -c 'clipse $fish_pid' `

Thanks a lot!

**Comment by savedra1** [comment]
> both echo $PPID and echo $PID return nothing. ![image](https://private-user-images.githubusercontent.com/58268/313411967-9f854cd8-4457-4cba-a3c7-95b9b3b76328.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA2MDEwMjksIm5iZiI6MTcxMDYwMDcyOSwicGF0aCI6Ii81ODI2OC8zMTM0MTE5NjctOWY4NTRjZDgtNDQ1Ny00Y2JhLWEzYzctOTViOWIzYjc2MzI4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE2VDE0NTIwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVkMjkxNWY5MjQ4YzZiNWEzMjg1YzNiMjJlYjA0MjYzZmEyMmUzMmVjMTIzYmZlZjg0NzE1NGUyZTQyZTg3M2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Ad8dWubIl63GTPSig2OXSK6AKkFP_miariRai4IuN8A)

So there we have our issue - is fish does not return a $PPID, the command was just running `clipse` in the binding, opening the TUI in persist mode. 

Looks like this might need a different var instead: https://github.com/fish-shell/fish-shell/issues/6203

**Comment by savedra1** [comment]
> So yeah, this bind works for me in fish: `bind = CONTROL ALT, C, exec, kitty --class floating -e fish -c 'clipse $fish_pid' `
> 
> Thanks a lot!

Excellent! glad you found a fix :)
