### ISSUE TITLE
Not working in Hyprland with foot terminal

### ISSUE THREAD

**Issue by cpnfeeny** [savedra1/clipse#20]
### Description
With foot terminal, the suggested Hyperland config doesn't work. No terminal will appear when entering the shortcut. 

However, it works perfectly if I use alacritty instead.

### Setup
hyprland.conf
```
exec-once = clipse -listen 
windowrulev2 = float,class:(floating)
bind = SUPER, B, exec, foot --class floating -e fish -c 'clipse $PPID'
```

### System Info
NixOS 24.05 
Hyprland 0.36.0
clipse 1.0.0
foot 1.16.2

**Comment by HirschBerge** [comment]
Looking at the [manual](https://man.archlinux.org/man/foot.1.en) are you sure that foot actually supports that like kitty or alacrity do? I don't see that as a given option. Maybe if you real the manual you'll find an alternative.

Also, having `<terminal> --class` in the readme assuming all terminals have the same implementation might not be the best way to do it.

**Comment by savedra1** [comment]
Thanks for raising @cpnfeeny. Looks like someone from the Hl reddit found a workaround for using foot, see [this comment](https://www.reddit.com/r/hyprland/comments/1bfdpyb/comment/kv4gv2o/?utm_source=share&utm_medium=web2x&context=3).  

Agreed @HirschBerge - I will get the advice updated.
