### ISSUE TITLE
Integration with other backends

### ISSUE THREAD

**Issue by Heus-Sueh** [savedra1/clipse#40]
Do you intend to integrate the project with other backends such as: [cliphist](https://github.com/sentriz/cliphist), [clipman](https://github.com/chmouel/clipman) or [copyq](https://github.com/hluk/CopyQ)?

I ask this because some or all of those I mentioned store the history in some .json that clipse could read instead of creating one of its own

**Comment by savedra1** [comment]
Hi @Heus-Sueh, 

Thank you for raising this! 

To answer your question, this would not be planned as the goal of `clipse` is to be it's own self-sufficient clipboard and the only one needed. Furthermore, `clipse` also uses a different json schema to any of those examples given to support the specific Bubbletea formatting in use, meaning a considerable amount if logic/refactor would be required to achecive a `one size fits all`. Essentially, the benefit from implementing this would not be worth the complexity/ engineering effort.

I would also add that the history file used for `clipse` can be redefined in the `config.json` file, meaning this could be set to the same json file that `clipman`/`copyq` use, but the schema used there would cause a panic when `clipse` tries to pass the data.

I hope that explains well enough and I will close this as `Wont do` for now but feel free to respond if you think I've missed anything :smile:
