### ISSUE TITLE
[Feature request] Copy multiple entries at once

### ISSUE THREAD

**Issue by kohane27** [savedra1/clipse#42]
Hello! Hope you're doing well. Thank you for creating this terminal-focused clipboard utility!

It'd be great if `clipse` has the ability to copy multiple entries at once, something like below:

1. Ctrl-down (or some other keybindings) to visually select multiple entries
2. Press `copy` command
3. All entries (separated by new lines) are copied to the clipboard

Maybe even something like below:

1. fuzzy search `abc`
2. Press `copy` command
3. fuzzy search `def`
4. Press `copy` command

Result: both `abc` and `def` entries (separated by new lines) are copied to the clipboard.

Thank you!

**Comment by savedra1** [comment]
Hey @kohane27, thank you for raising this! 

I think this is a really great idea. Hadn't even considered it until now but I can totally see that being useful. I'll explore the possabilities for this in Bubbletea and aim to get this added to the next release :sunglasses: 

Will keep you updated on any progress

**Comment by savedra1** [comment]
@kohane27 This feature has now been implemented in [v1.0.0](https://github.com/savedra1/clipse/releases/tag/v1.0.0) :partying_face: 

Updated Nix and AUR packages coming soon.

Thanks again for the idea!

**Comment by kohane27** [comment]
Thank you so much for implementing this feature!
I just tried and it works wonderfully <3
Thanks again!
