### ISSUE TITLE
Can't paste copied item.

### ISSUE THREAD

**Issue by jeatog** [savedra1/clipse#46]
Hello! First of all this a very simple and beautiful TUI clipboard manager that seamlessly integrates with my environment. Thanks for that!

I'm having a problem right now, though. The clipse --listen command works well and it registers everything I copy. But when I want to paste it anywhere it does nothing at all. So I decided to see what happens when clipse -p and I get this exit.

![Shot-2024-05-15-165850](https://github.com/savedra1/clipse/assets/109049666/e7450f87-5270-4385-a908-80de513f1973)

Could anyone help me, please? Perhaps I forgot to add or config something. If you need more info I'll also share it.

Thanks!

**Comment by savedra1** [comment]
Ah thanks for letting me know @jeatog 

it looks like this is the same issue as #45 then so I will close this one and add any further updates in there. If you find a fix I'd love to know for my own curiosity.

The copy mechanism used by clipse for X environments is `xclip -in -selection clipboard` but I think the alacritty session ending also ends the connection to the X server. Was thinking you could try piping the copied input while in the session to `xclip -selection clipboard` to see if that helps.. Something like:
`alacritty -e clipse | clipboard_contents=$(xclip -selection clipboard -o) && echo '$clipboard_contents' | xclip -selection clipboard` 

Not sure if that will help though as I'm unable to test an X environment atm. 

Apologies I can't be of more help at this time but thank you again for trying clipse! :blue_heart:
