### ISSUE TITLE
hyprland exec-once = clipse -listen not working on Nixos

### ISSUE THREAD

**Issue by mononomori** [savedra1/clipse#51]
Distro Nixos.

Currently the hyprland startup execution isn't working for me. All my other exec-once programs work as intended so not sure why. If I manually run clipse -listen in a terminal, it works as intended (even after killing that terminal).

Any ideas?

**Comment by savedra1** [comment]
Hey @mononomori :wave: thanks for raising this.

I'm not 100% sure why that's not working for you as it sounds like you have the same desktop setup as me. For some context, the `clipse -listen` command executes the sub-command `nohup clipse --listen-shell >/dev/null 2>&1 &`. Would your config have any issues with this during boot? 

You could try substituting `exec-once = clipse -listen` for `nohup clipse --listen-shell >/dev/null 2>&1 &`, calling the sub command directly instead to see if that helps. 

Assuming you confirmed you Nix flake/env was definitely rebuilt successfully after you added the `exec-once` cmd. 

Only alternatives I can think of is to use a systemd service or a .desktop file but would rather avoid that ofc.

**Comment by mononomori** [comment]
`nohup clipse --listen-shell >/dev/null 2>&1 &` Didn't seem to work for me but on a whim I tried adding a 2 second to the startup execution `exec-once sleep 2; -listen` 
That seems to have fixed the issue but I'm not really sure why? My hyprland setup is super minimal right now when it comes to startup executions, it's literally just:

```
exec-once = waybar
exec-once = nm-applet
exec-once = blueman-applet
exec-once = sleep 2; clipse -listen

```

**Comment by savedra1** [comment]
@mononomori thanks for the update!

That is interesting, I'm not sure why that's fixed it either. Any errors that would arise from not being able to access the system clipboard on boot are ignored by the clipse binary so shouldn't be causing a panic. 

I'm glad to hear you've found a decent work around though! I'll investigate this further before the next release, although it's difficult for me to replicate :thinking:

**Comment by mononomori** [comment]
Yeah it makes even less sense, because previously when even when reloading hyprland after boot, it wouldn't fix the issue, which should have ruled out any issues with it potentially loading before wl-clipboard.

**Comment by mononomori** [comment]
I'm on 0.40.0 so probably not anything to do with that.

It's probably like you say, some niche hardware interaction.

Thanks for your help, if I figure anything else out in the future I'll let you!
