### ISSUE TITLE
Theming improvements

### ISSUE THREAD

**Issue by maydayv7** [savedra1/clipse#59]
![Clipse Window](https://github.com/savedra1/clipse/assets/73811274/2f30607f-cdd6-4947-a792-6bb8eec09c63)

Also, it would be nice if 'No items' is only shown once when status is enabled

**Comment by savedra1** [comment]
Thank you for suggesting this @maydayv7, I agree this is a needed enhancement. 

The color used for the filter search is could be included here also _(currently always yellow)_. 

There might be some limitations here regarding what's possible with `BubbleTea` but I'll investigate when I get a chance :smile:

**Comment by savedra1** [comment]
@maydayv7 This feature has now been implemented in [v1.0.0](https://github.com/savedra1/clipse/releases/tag/v1.0.0) 🥳

Updated Nix and AUR packages coming soon. 

Thanks again for the suggestion!
