### ISSUE TITLE
Clipboard Time Stamps out of sync with system time

### ISSUE THREAD

**Issue by mononomori** [savedra1/clipse#64]
My NixOS Version: Unstable

I just noticed that the time stamps for Date Copied: are out of sync with my system time. I have my time-zone manually set in my configuration file, but even with removing that and using something like `automatic-timezoned` to see if it being automatically adjusted would change anything but that didn't work. The date, minutes, and seconds are all accurate, so I have a feeling it somehow thinks my timezone is different? Not sure. 

![screenshot_2024-06-06-155237](https://github.com/savedra1/clipse/assets/60534233/8e47017c-55b1-4d75-8d48-9323b7a802e8)

**Comment by savedra1** [comment]
Hi @mononomori 🫡

Thanks for pointing this out! It looks like the code is converting the local time into UTC, so definitely nothing you're missing here. 

This should be a super quick fix, I'll make the update asap and update you here.

**Comment by savedra1** [comment]
@mononomori update merged. It will be included in the stable/unstable Nix package as part of the next release and could be rebuilt from the last commit in the meantime. Thanks again for raising :handshake:

**Comment by mononomori** [comment]
Aweesome, thanks for the quick response time!
